services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    env_file:
      - .env.local
    ports:
      - "5672:5672"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    restart: always
    env_file:
      - .env.local
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./keycloak/dev-realm.json:/opt/keycloak/data/import/myrealm.json
    command: start-dev --import-realm

volumes:
  postgres_data:
