apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.name }}
  namespace: cert-manager
spec:
  acme:
    email: levin@uncu.de
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.tlsSecretName }}
    solvers:
      - http01:
          ingress:
            ingressClassName: "nginx"
