apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.secretStoreName }}
  target:
    name: {{ .Values.name }}
    creationPolicy: Owner
  data:
{{ toYaml .Values.data | indent 4 }}