apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.disk.size }}
  volumeName: {{ .Values.volume.name }}