apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: default
  capacity:
    storage: {{ .Values.capacityStorage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: disk.csi.azure.com
    volumeHandle: {{ .Values.volumeHandle }}
    fsType: ext4